# orchestrator_stix.py
import json
import uuid
import datetime
import os

# 1. Output Dateiname
OUTPUT_STIX_FILE = "Test_STIX.json"

print("🔹 ORCHESTRATOR: Generiere STIX Report aus Inference-Daten...")

# 2. Daten abgreifen & Sicherstellen, dass Listen existieren
detected_cpes = []
detected_techniques = []

# A. CPEs holen
if 'final_cpe_results' in globals() and final_cpe_results:
    # Wir übernehmen die ganze Liste
    detected_cpes = final_cpe_results
    print(f"   ✅ {len(detected_cpes)} CPEs übernommen.")
else:
    print("   ⚠️ Keine CPEs gefunden.")

# B. Techniques holen
if 'results' in globals() and results:
    # results ist eine Liste von Tuples: (id, name, score)
    # Wir wandeln das in eine Liste von Dictionaries um
    for item in results:
        detected_techniques.append({
            "id": item[0],
            "name": item[1],
            "score": float(item[2])
        })
    print(f"   ✅ {len(detected_techniques)} Techniken übernommen.")
else:
    print("   ⚠️ Keine Techniken gefunden.")


# 3. Das STIX Objekt bauen (Erweitert für Listen)
stix_output = {
  "type": "report",
  "id": str(uuid.uuid4()),
  "created": datetime.datetime.now(datetime.timezone.utc).isoformat(),
  "name": "Automated Threat Intel Report",
  "description": "Generated by text2CPE and text2Technique Inference.",
  
  # --- NEU: Listen statt Einzelwerte ---
  "x_detected_techniques": detected_techniques,
  "x_detected_cpes": detected_cpes,
  
  # --- LEGACY SUPPORT (Optional) ---
  # Wir setzen den besten Match auch in die alten Felder, falls der Loader noch alt ist
  "technique": detected_techniques[0]['id'] if detected_techniques else "T0000",
  "cpe": detected_cpes[0]['cpe23'] if detected_cpes else "cpe:2.3:*:*:*:*:*:*:*:*:*:*:*"
}

# 4. Speichern
try:
    with open(OUTPUT_STIX_FILE, "w", encoding="utf-8") as f:
        json.dump(stix_output, f, indent=2)
    print(f"💾 STIX Report gespeichert: {os.path.abspath(OUTPUT_STIX_FILE)}")
except Exception as e:
    print(f"❌ Fehler beim Speichern des STIX Reports: {e}")
